/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Bussiness.Airline;
import Bussiness.AirlineDirectory;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author vaniv
 */
public class ManageAirlinersJPanel extends javax.swing.JPanel {
    private JPanel rightPanel;
    private  AirlineDirectory airlineDirectory;
    Airline airline;
    /**
     * Creates new form ManageAirlinersJPanel
     */
    public ManageAirlinersJPanel(JPanel rightPanel, AirlineDirectory airlineDirectory) {
        initComponents();
        this.rightPanel = rightPanel;
        this.airlineDirectory = airlineDirectory;
        populate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CreateAirlineBtn = new javax.swing.JButton();
        DeleteAirlinebtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        AirlineTable = new javax.swing.JTable();
        viewBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 0, 0));

        CreateAirlineBtn.setBackground(new java.awt.Color(0, 51, 102));
        CreateAirlineBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        CreateAirlineBtn.setForeground(new java.awt.Color(255, 255, 255));
        CreateAirlineBtn.setText("CREATE NEW AIRLINE");
        CreateAirlineBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateAirlineBtnActionPerformed(evt);
            }
        });

        DeleteAirlinebtn.setBackground(new java.awt.Color(0, 51, 102));
        DeleteAirlinebtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        DeleteAirlinebtn.setForeground(new java.awt.Color(255, 255, 255));
        DeleteAirlinebtn.setText("DELETE");
        DeleteAirlinebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteAirlinebtnActionPerformed(evt);
            }
        });

        backBtn.setBackground(new java.awt.Color(0, 51, 102));
        backBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        backBtn.setForeground(new java.awt.Color(255, 255, 255));
        backBtn.setText("<< BACK");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        AirlineTable.setBackground(new java.awt.Color(0, 51, 102));
        AirlineTable.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(0, 0, 0), null, null));
        AirlineTable.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        AirlineTable.setForeground(new java.awt.Color(255, 255, 255));
        AirlineTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "AIRLINE NAME", "AIRLINE ID"
            }
        ));
        jScrollPane1.setViewportView(AirlineTable);

        viewBtn.setBackground(new java.awt.Color(0, 51, 102));
        viewBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        viewBtn.setForeground(new java.awt.Color(255, 255, 255));
        viewBtn.setText("VIEW");
        viewBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(140, 140, 140)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(backBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE)
                        .addGap(32, 32, 32)
                        .addComponent(viewBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE)
                        .addGap(27, 27, 27)
                        .addComponent(DeleteAirlinebtn, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE)
                        .addGap(32, 32, 32)
                        .addComponent(CreateAirlineBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE)))
                .addGap(132, 132, 132))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(viewBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(DeleteAirlinebtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CreateAirlineBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(47, 47, 47))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
     rightPanel.remove(this);
       CardLayout Layout = (CardLayout)rightPanel.getLayout();
       Layout.previous(rightPanel);
//       Component[] components = rightPanel.getComponents();
//       for(Component c : components){
//           if(c instanceof ManageAirlinersJPanel){
//               ManageAirlinersJPanel panel = (ManageAirlinersJPanel)c;
//               panel.populate();
//           }
       //}
    }//GEN-LAST:event_backBtnActionPerformed

    private void DeleteAirlinebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteAirlinebtnActionPerformed
       int selectedrow = AirlineTable.getSelectedRow();
        if (selectedrow >= 0)
        {
           int selectionButton = JOptionPane.YES_NO_OPTION;
            int selectionResult = JOptionPane.showConfirmDialog(null, "Are you sure to delete??","Warning",selectionButton);
            if(selectionResult == JOptionPane.YES_OPTION){
                Airline air = (Airline)AirlineTable.getValueAt(selectedrow, 0);
                airlineDirectory.deleteAirline(air);
                populate();
            }
        }else{
            JOptionPane.showMessageDialog(null, "Please select a Row!!");
        }
    }//GEN-LAST:event_DeleteAirlinebtnActionPerformed

    private void CreateAirlineBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateAirlineBtnActionPerformed
        CreateAirlineJPanel createAirlineJPanel = new CreateAirlineJPanel(rightPanel,airlineDirectory);
        rightPanel.add("CreateJPanel" , createAirlineJPanel);
        CardLayout Layout = (CardLayout)rightPanel.getLayout();
        Layout.next(rightPanel);
    }//GEN-LAST:event_CreateAirlineBtnActionPerformed

    private void viewBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewBtnActionPerformed
      int row = AirlineTable.getSelectedRow();
        if(row<0) {
            JOptionPane.showMessageDialog(null, "Please select a row from the table first", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        Airline a = (Airline)AirlineTable.getValueAt(row, 0);
        ViewJPanel viewAirlineJPanel = new ViewJPanel(rightPanel,a);
       rightPanel.add("ViewJPanel" , viewAirlineJPanel);
        CardLayout Layout = (CardLayout)rightPanel.getLayout();
        Layout.next(rightPanel);
    }//GEN-LAST:event_viewBtnActionPerformed
    public void populate(){
        DefaultTableModel dtm = (DefaultTableModel)AirlineTable.getModel();
        dtm.setRowCount(0);
        for(Airline a : airlineDirectory.getAirlineDirectory()){
            Object[] row = new Object[dtm.getColumnCount()];
            row[0]=a;
            row[1]=a.getAirlineID();
            dtm.addRow(row);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable AirlineTable;
    private javax.swing.JButton CreateAirlineBtn;
    private javax.swing.JButton DeleteAirlinebtn;
    private javax.swing.JButton backBtn;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton viewBtn;
    // End of variables declaration//GEN-END:variables
}
