/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Bussiness.Airline;
import Bussiness.AirlineDirectory;
import Bussiness.Customer;
import Bussiness.Flight;
import Bussiness.Seats;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author vaniv
 */
public class SeatAssignmentJPanel extends javax.swing.JPanel {

    /**
     * Creates new form SeatAssignmentJPanel
     */
    private JPanel rightPanel;
    private Airline air;
   
    
    
    SeatAssignmentJPanel(JPanel rightPanel,Airline air) {
        initComponents();
        this.rightPanel = rightPanel;
        this.air =air;
        airlineName.setText(air.getAirlineName());
            for(Flight flight : air.getFlightdir().getFlightDirectory()){
                From.setText(flight.getDepartLocation());
                To.setText(flight.getArrivalLocation());
        }        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        airlineName = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        From = new javax.swing.JTextPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        To = new javax.swing.JTextPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        WindowTable = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        AisleTable = new javax.swing.JTable();
        jScrollPane8 = new javax.swing.JScrollPane();
        MiddleTable = new javax.swing.JTable();

        setBackground(new java.awt.Color(0, 0, 0));

        airlineName.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jScrollPane1.setViewportView(airlineName);

        From.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jScrollPane2.setViewportView(From);

        To.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jScrollPane3.setViewportView(To);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("FROM");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("TO");

        WindowTable.setBackground(new java.awt.Color(0, 51, 102));
        WindowTable.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        WindowTable.setForeground(new java.awt.Color(255, 255, 255));
        WindowTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"A1"},
                {"A6"},
                {"B1"},
                {"B6"},
                {"C1"},
                {"C6"},
                {"D1"},
                {"D6"},
                {"E1"},
                {"E6"},
                {"F1"},
                {"F6"},
                {"G1"},
                {"G6"},
                {"H1"},
                {"H6"},
                {"I1"},
                {"I6"},
                {"J1"},
                {"J6"},
                {"K1"},
                {"K6"},
                {"L1"},
                {"L6"},
                {"M1"},
                {"M6"},
                {"N1"},
                {"N6"},
                {"O1"},
                {"O6"},
                {"P1"},
                {"P6"},
                {"Q1"},
                {"Q6"},
                {"R1"},
                {"R6"},
                {"S1"},
                {"S6"},
                {"T1"},
                {"T6"},
                {"U1"},
                {"U6"},
                {"V1"},
                {"V6"},
                {"X1"},
                {"X6"},
                {"Y1"},
                {"Y6"},
                {"Z1"},
                {"Z6"}
            },
            new String [] {
                "SEATS"
            }
        ));
        jScrollPane4.setViewportView(WindowTable);

        jButton1.setBackground(new java.awt.Color(0, 51, 102));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("SELECT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("AIRLINE");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("WINDOW SEATS");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("MIDDLE SEATS");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("AISLE SEATS");

        AisleTable.setBackground(new java.awt.Color(0, 51, 102));
        AisleTable.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        AisleTable.setForeground(new java.awt.Color(255, 255, 255));
        AisleTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"A2"},
                {"A5"},
                {"B2"},
                {"B5"},
                {"C2"},
                {"C5"},
                {"D2"},
                {"D5"},
                {"E2"},
                {"E5"},
                {"F2"},
                {"F5"},
                {"G2"},
                {"G5"},
                {"H2"},
                {"H5"},
                {"I2"},
                {"I5"},
                {"J2"},
                {"J5"},
                {"K2"},
                {"K5"},
                {"L2"},
                {"L5"},
                {"M2"},
                {"M5"},
                {"N2"},
                {"N5"},
                {"O2"},
                {"O5"},
                {"P2"},
                {"P5"},
                {"Q2"},
                {"Q5"},
                {"R2"},
                {"R5"},
                {"S2"},
                {"S5"},
                {"T2"},
                {"T5"},
                {"U2"},
                {"U5"},
                {"V2"},
                {"V5"},
                {"X2"},
                {"X5"},
                {"Y2"},
                {"Y5"},
                {"Z2"},
                {"Z5"}
            },
            new String [] {
                "SEATS"
            }
        ));
        jScrollPane5.setViewportView(AisleTable);

        MiddleTable.setBackground(new java.awt.Color(0, 51, 102));
        MiddleTable.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        MiddleTable.setForeground(new java.awt.Color(255, 255, 255));
        MiddleTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"A3"},
                {"A4"},
                {"B3"},
                {"B4"},
                {"C3"},
                {"C4"},
                {"D3"},
                {"D4"},
                {"E3"},
                {"E4"},
                {"F3"},
                {"F4"},
                {"G3"},
                {"G4"},
                {"H3"},
                {"H4"},
                {"I3"},
                {"I4"},
                {"J3"},
                {"J4"},
                {"K3"},
                {"K4"},
                {"L3"},
                {"L4"},
                {"M3"},
                {"M4"},
                {"N3"},
                {"N4"},
                {"O3"},
                {"O4"},
                {"P3"},
                {"P4"},
                {"Q3"},
                {"Q4"},
                {"R3"},
                {"R4"},
                {"S3"},
                {"S4"},
                {"T3"},
                {"T4"},
                {"U3"},
                {"U4"},
                {"V3"},
                {"V4"},
                {"X3"},
                {"X4"},
                {"Y3"},
                {"Y4"},
                {"Z3"},
                {"Z4"}
            },
            new String [] {
                "SEATS"
            }
        ));
        jScrollPane8.setViewportView(MiddleTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 247, Short.MAX_VALUE)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(245, 245, 245)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(92, 92, 92))
            .addGroup(layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(jLabel4)
                .addGap(280, 280, 280)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(140, 140, 140))
            .addGroup(layout.createSequentialGroup()
                .addGap(532, 532, 532)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jScrollPane1, jScrollPane2, jScrollPane3});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(54, 54, 54)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(46, 46, 46))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jScrollPane1, jScrollPane2, jScrollPane3});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel1, jLabel2});

    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int selectRow = WindowTable.getSelectedRow();
        if(selectRow>0){
           
            for(Flight flight : air.getFlightdir().getFlightDirectory()){
                for(Customer customer:flight.getCustomerdir().getCustomerDirectory()){
                    Seats seat = customer.getSeatDir().addSeat();
                    seat.setSelectedSeat((String) WindowTable.getValueAt(selectRow,0));
                    seat.setSeatName("Window Seat");
                    int flightseat = flight.getAvailableSeats();
                    flightseat = flightseat -1;
                    flight.setAvailableSeats(flightseat);
                    ((DefaultTableModel)WindowTable.getModel()).removeRow(WindowTable.getSelectedRow());
                    JOptionPane.showMessageDialog(null,"Seat selection successful");
                    PaymentJPanel paymentJPanel = new PaymentJPanel(rightPanel,air);
                    rightPanel.add("paymentJPanel" , paymentJPanel);
                    CardLayout Layout = (CardLayout)rightPanel.getLayout();
                    Layout.next(rightPanel);
                }
            }
        }
        int SelectRow =MiddleTable.getSelectedRow();
        if(SelectRow>0){
          
              for(Flight flight : air.getFlightdir().getFlightDirectory()){
                for(Customer customer:flight.getCustomerdir().getCustomerDirectory()){
                    Seats seat = customer.getSeatDir().addSeat();
                    seat.setSelectedSeat((String) MiddleTable.getValueAt(SelectRow,0));
                    seat.setSeatName("Middle Seat");
                    int flightseat = flight.getAvailableSeats();
                    flightseat = flightseat -1;
                    flight.setAvailableSeats(flightseat);
                    ((DefaultTableModel)MiddleTable.getModel()).removeRow(MiddleTable.getSelectedRow());
                     JOptionPane.showMessageDialog(null,"Seat selection successful");
                     PaymentJPanel paymentJPanel = new PaymentJPanel(rightPanel,air);
                    rightPanel.add("paymentJPanel" , paymentJPanel);
                    CardLayout Layout = (CardLayout)rightPanel.getLayout();
                    Layout.next(rightPanel);
            }
          }
        }  
        int selectrow =AisleTable.getSelectedRow();
        if(selectrow>0){
              for(Flight flight : air.getFlightdir().getFlightDirectory()){
                for(Customer customer:flight.getCustomerdir().getCustomerDirectory()){
                    Seats seat = customer.getSeatDir().addSeat();
                    seat.setSelectedSeat((String) AisleTable.getValueAt(selectrow,0));
                    seat.setSeatName("Aisle Seat");
                    int flightseat = flight.getAvailableSeats();
                    flightseat = flightseat -1;
                    flight.setAvailableSeats(flightseat);
                    ((DefaultTableModel)AisleTable.getModel()).removeRow(AisleTable.getSelectedRow());
                     JOptionPane.showMessageDialog(null,"Seat selection successful");
                     PaymentJPanel paymentJPanel = new PaymentJPanel(rightPanel,air);
                    rightPanel.add("paymentJPanel" , paymentJPanel);
                    CardLayout Layout = (CardLayout)rightPanel.getLayout();
                    Layout.next(rightPanel);
                }
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable AisleTable;
    private javax.swing.JTextPane From;
    private javax.swing.JTable MiddleTable;
    private javax.swing.JTextPane To;
    private javax.swing.JTable WindowTable;
    private javax.swing.JTextPane airlineName;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane8;
    // End of variables declaration//GEN-END:variables
}
