/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Bussiness.Airline;
import Bussiness.AirlineDirectory;
import Bussiness.Customer;
import Bussiness.Flight;
import Bussiness.Payment;
import Bussiness.Seats;
import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author vaniv
 */
public class ViewReservationJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewReservationJPanel
     */
    private JPanel rightPanel;
    private AirlineDirectory air;

    ViewReservationJPanel(JPanel rightPanel, AirlineDirectory air) {
         initComponents();
         this.rightPanel = rightPanel;
         this.air = air;
         populate();
    }

    public void populate(){
        DefaultTableModel dtm = (DefaultTableModel)ReservationTable.getModel();
        dtm.setRowCount(0);
        for(Airline air : air.getAirlineDirectory()){
        for(Flight flight : air.getFlightdir().getFlightDirectory()){
            for(Customer customer : flight.getCustomerdir().getCustomerDirectory()){
                for(Seats Seat :customer.getSeatDir().getSeatDirectory()){
                    for(Payment payment : customer.getPaymentDir().getPaymentDirectory()){
                    Object[] row = new Object[dtm.getColumnCount()];
                    row[0]=customer;
                    row[1]=Seat.getSelectedSeat();
                    row[2]=flight.getDepartLocation();
                    row[3]=flight.getArrivalLocation();
                    row[4]=flight.getDate();
                    row[5]=flight.getDepartTime();
                    row[6]=payment.getPaymentMethod();
                    dtm.addRow(row);
                    }
                }
            }
         }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        ReservationTable = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 0, 0));

        ReservationTable.setBackground(new java.awt.Color(0, 51, 102));
        ReservationTable.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ReservationTable.setForeground(new java.awt.Color(255, 255, 255));
        ReservationTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CUSTOMER NAME", "SEAT", "DEPARTURE LOCATION", "ARRIVAL LOCATION", "DATE", "TIME ", "PAYMENT METHOD"
            }
        ));
        jScrollPane1.setViewportView(ReservationTable);

        jButton1.setBackground(new java.awt.Color(0, 51, 102));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("<< BACK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(590, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(595, 595, 595))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 646, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jButton1)
                .addContainerGap(21, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        rightPanel.remove(this);
        CardLayout layout = (CardLayout) rightPanel.getLayout();
        layout.previous(rightPanel);
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable ReservationTable;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
