/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;
import Business.Person;
import Business.Address;

/**
 *
 * @author vaniv
 */
public class PersonJPanel extends javax.swing.JPanel {

    /**
     * Creates new form PersonJPanel
     */
  
    public PersonJPanel(Person person,Address LocalAddress,Address WorkAddress,Address HomeAddress) {
        initComponents();
        displayPerson(person , LocalAddress,WorkAddress ,HomeAddress);
    }
    
    //Extraction of the data for display 
   private void displayPerson(Person person, Address LocalAddress ,Address WorkAddress, Address HomeAddress){
       String FN = person.getFirstName();
       FirstName.setText(FN);
       String LN = person.getLastName();
       LastName.setText(LN);
       String Streetaddress = person.getStreetAddress();
       StreetAddress.setText(Streetaddress);
       String Dob = person.getDOB();
       DOB.setText(Dob);
       
       String LocalA= LocalAddress.getLocalAddressStreetline1();
       LocalAddressStreetLine1.setText(LocalA);
       String LocalA2=LocalAddress.getLocalAddressStreetline2();
       LocalAddressStreetLine2.setText(LocalA2);
       String LocalC = LocalAddress.getLocalAddressCity();
       LocalAddressCity.setText(LocalC);
       String LocalS = LocalAddress.getLocalAddressState();
       LocalAddressState.setText(LocalS);
       String LocalZ = LocalAddress.getLocalAddresszipCode();
       LocalAddressZipCode.setText(LocalZ);
       String LocalCo = LocalAddress.getLocalAddressCountry();
       LocalAddressCountry.setText(LocalCo);
       
       String WorkA = WorkAddress.getWorkAddressStreetLine1();
       WorkAddressStreetLine1.setText(WorkA);
       String WorkA2=WorkAddress.getWorkAddressStreetLine2();
       WorkAddressStreetLine2.setText(WorkA2);
       String WorkC = WorkAddress.getWorkAddressCity();
       WorkAddressCity.setText(WorkC);
       String WorkS = WorkAddress.getWorkAddressState();
       WorkAddressState.setText(WorkS);
       String WorkZ = WorkAddress.getWorkAddresszipCode();
       WorkAddressZipCode.setText(WorkZ);
       String WorkCo = WorkAddress.getWorkAddressCountry();
       WorkAddressCountry.setText(WorkCo);
       
       
       String HomeA = HomeAddress.getHomeAddressStreetline1();
       HomeAddressStreetLine1.setText(HomeA);
       String Home2=HomeAddress.getHomeAddressStreetline2();
       HomeAddressStreetLine2.setText(Home2);
       String HomeC = HomeAddress.getHomeAddressCity();
       HomeAddressCity.setText(HomeC);
       String HomeS = HomeAddress.getHomeAddressState();
       HomeAddressState.setText(HomeS);
       String HomeZ = HomeAddress.getHomeAddresszipCode();
       HomeAddressZipCode.setText(HomeZ);
       String HomeCo = HomeAddress.getHomeAddressCountry();
       HomeAddressCountry.setText(HomeCo);
       
       
   }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        FirstNameLabel = new javax.swing.JLabel();
        LastNameLabel = new javax.swing.JLabel();
        StreetAddressLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        StreetAddress = new javax.swing.JTextArea();
        FirstName = new javax.swing.JTextField();
        LastName = new javax.swing.JTextField();
        DOBLabel = new javax.swing.JLabel();
        DOB = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        LocalAddressStateLabel = new javax.swing.JLabel();
        LocalAddressZipCodelabel = new javax.swing.JLabel();
        LocalAddressCountryLabel = new javax.swing.JLabel();
        LocalAddressStreetLine1 = new javax.swing.JTextField();
        LocalAddressStreetLine2 = new javax.swing.JTextField();
        LocalAddressCity = new javax.swing.JTextField();
        LocalAddressState = new javax.swing.JTextField();
        LocalAddressZipCode = new javax.swing.JTextField();
        LocalAddressCountry = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        HomeAddressStreetLine1Label = new javax.swing.JLabel();
        HomeAddressStreetLine2Label = new javax.swing.JLabel();
        HomeAddressCityLabel = new javax.swing.JLabel();
        HomeAddressStateLabel = new javax.swing.JLabel();
        HomeAddressZipCodeLabel = new javax.swing.JLabel();
        HomeAddressCountryLabel = new javax.swing.JLabel();
        HomeAddressStreetLine1 = new javax.swing.JTextField();
        HomeAddressStreetLine2 = new javax.swing.JTextField();
        HomeAddressCity = new javax.swing.JTextField();
        HomeAddressState = new javax.swing.JTextField();
        HomeAddressZipCode = new javax.swing.JTextField();
        HomeAddressCountry = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        WorkAddressStreetLine1Label = new javax.swing.JLabel();
        WorkAddressStreetLine2Label = new javax.swing.JLabel();
        WorkAddressCityLabel = new javax.swing.JLabel();
        WorkAddressStatelabel = new javax.swing.JLabel();
        WorkAddressZipCodeLabel = new javax.swing.JLabel();
        WorkAddressCountryLabel = new javax.swing.JLabel();
        WorkAddressStreetLine1 = new javax.swing.JTextField();
        WorkAddressStreetLine2 = new javax.swing.JTextField();
        WorkAddressCity = new javax.swing.JTextField();
        WorkAddressState = new javax.swing.JTextField();
        WorkAddressZipCode = new javax.swing.JTextField();
        WorkAddressCountry = new javax.swing.JTextField();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("PERSON PROFILE");

        FirstNameLabel.setText("FIRST NAME");

        LastNameLabel.setText("LAST NAME");

        StreetAddressLabel.setText("STREET ADDRESS");

        StreetAddress.setColumns(20);
        StreetAddress.setRows(5);
        jScrollPane1.setViewportView(StreetAddress);

        LastName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LastNameActionPerformed(evt);
            }
        });

        DOBLabel.setText("DOB (YYYY/MM/DD)");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Local Address"));
        jPanel1.setPreferredSize(new java.awt.Dimension(300, 30));

        jLabel6.setText("Street Line 1");

        jLabel7.setText("Street Line 2");

        jLabel8.setText("City");

        LocalAddressStateLabel.setText("State");

        LocalAddressZipCodelabel.setText("Zip Code");

        LocalAddressCountryLabel.setText("Country");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 24, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(LocalAddressStreetLine1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(LocalAddressStreetLine2, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(LocalAddressCity, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(LocalAddressStateLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(LocalAddressState, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(LocalAddressZipCodelabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(LocalAddressZipCode, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(LocalAddressCountryLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(LocalAddressCountry, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {LocalAddressCountryLabel, LocalAddressStateLabel, LocalAddressZipCodelabel, jLabel6, jLabel7, jLabel8});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {LocalAddressCity, LocalAddressCountry, LocalAddressState, LocalAddressStreetLine1, LocalAddressStreetLine2, LocalAddressZipCode});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(LocalAddressStreetLine1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(LocalAddressStreetLine2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(LocalAddressCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LocalAddressStateLabel)
                    .addComponent(LocalAddressState, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LocalAddressZipCodelabel)
                    .addComponent(LocalAddressZipCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LocalAddressCountryLabel)
                    .addComponent(LocalAddressCountry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {LocalAddressCountryLabel, LocalAddressStateLabel, LocalAddressZipCodelabel, jLabel6, jLabel7, jLabel8});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {LocalAddressCity, LocalAddressCountry, LocalAddressState, LocalAddressStreetLine1, LocalAddressStreetLine2, LocalAddressZipCode});

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Home Address"));

        HomeAddressStreetLine1Label.setText("Street Line 1");

        HomeAddressStreetLine2Label.setText("Street Line 2");

        HomeAddressCityLabel.setText("City");

        HomeAddressStateLabel.setText("State");

        HomeAddressZipCodeLabel.setText("Zip Code");

        HomeAddressCountryLabel.setText("Country");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(HomeAddressStreetLine1Label, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                    .addComponent(HomeAddressStreetLine2Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(HomeAddressCityLabel)
                    .addComponent(HomeAddressStateLabel)
                    .addComponent(HomeAddressZipCodeLabel)
                    .addComponent(HomeAddressCountryLabel))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(HomeAddressStreetLine1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(HomeAddressStreetLine2, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(HomeAddressCity, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(HomeAddressState, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(HomeAddressZipCode, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(HomeAddressCountry, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {HomeAddressCityLabel, HomeAddressCountryLabel, HomeAddressStateLabel, HomeAddressStreetLine1Label, HomeAddressStreetLine2Label, HomeAddressZipCodeLabel});

        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(HomeAddressStreetLine1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(HomeAddressStreetLine2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(HomeAddressStreetLine2Label))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(HomeAddressCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(HomeAddressCityLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(HomeAddressState, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(HomeAddressStateLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(HomeAddressZipCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(HomeAddressZipCodeLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(HomeAddressCountry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(HomeAddressCountryLabel)))
                    .addComponent(HomeAddressStreetLine1Label))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {HomeAddressCityLabel, HomeAddressCountryLabel, HomeAddressStateLabel, HomeAddressStreetLine1Label, HomeAddressStreetLine2Label, HomeAddressZipCodeLabel});

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Work Address"));
        jPanel2.setPreferredSize(new java.awt.Dimension(300, 30));

        WorkAddressStreetLine1Label.setText("Street Line 1");

        WorkAddressStreetLine2Label.setText("Street Line 2");

        WorkAddressCityLabel.setText("City");

        WorkAddressStatelabel.setText("State");

        WorkAddressZipCodeLabel.setText("Zip Code");

        WorkAddressCountryLabel.setText("Country");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(WorkAddressStreetLine1Label, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                    .addComponent(WorkAddressStreetLine2Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(WorkAddressCityLabel)
                    .addComponent(WorkAddressStatelabel)
                    .addComponent(WorkAddressCountryLabel)
                    .addComponent(WorkAddressZipCodeLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(WorkAddressStreetLine1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(WorkAddressStreetLine2, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(WorkAddressCity, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(WorkAddressState, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(WorkAddressZipCode, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(WorkAddressCountry, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {WorkAddressCityLabel, WorkAddressCountryLabel, WorkAddressStatelabel, WorkAddressStreetLine1Label, WorkAddressStreetLine2Label, WorkAddressZipCodeLabel});

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {WorkAddressCity, WorkAddressCountry, WorkAddressState, WorkAddressStreetLine1, WorkAddressStreetLine2, WorkAddressZipCode});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(WorkAddressStreetLine1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(WorkAddressStreetLine1Label))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(WorkAddressStreetLine2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(WorkAddressStreetLine2Label))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(WorkAddressCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(WorkAddressCityLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(WorkAddressState, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(WorkAddressZipCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(WorkAddressZipCodeLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(WorkAddressCountry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(WorkAddressCountryLabel)))
                    .addComponent(WorkAddressStatelabel))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {WorkAddressCityLabel, WorkAddressCountryLabel, WorkAddressStatelabel, WorkAddressStreetLine1Label, WorkAddressStreetLine2Label, WorkAddressZipCodeLabel});

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {WorkAddressCity, WorkAddressCountry, WorkAddressState, WorkAddressStreetLine1, WorkAddressStreetLine2, WorkAddressZipCode});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 334, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(StreetAddressLabel)
                            .addComponent(FirstNameLabel)
                            .addComponent(LastNameLabel))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LastName, javax.swing.GroupLayout.PREFERRED_SIZE, 494, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jScrollPane1)
                                .addComponent(FirstName)))))
                .addGap(150, 150, 150)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(DOB)
                    .addComponent(DOBLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {FirstName, LastName});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {FirstNameLabel, LastNameLabel, StreetAddressLabel});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(FirstNameLabel)
                            .addComponent(FirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DOBLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(LastNameLabel))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(LastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(DOB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(StreetAddressLabel)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 336, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 336, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(51, 51, 51))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {FirstName, LastName});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {FirstNameLabel, LastNameLabel, StreetAddressLabel});

    }// </editor-fold>//GEN-END:initComponents

    private void LastNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LastNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LastNameActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField DOB;
    private javax.swing.JLabel DOBLabel;
    private javax.swing.JTextField FirstName;
    private javax.swing.JLabel FirstNameLabel;
    private javax.swing.JTextField HomeAddressCity;
    private javax.swing.JLabel HomeAddressCityLabel;
    private javax.swing.JTextField HomeAddressCountry;
    private javax.swing.JLabel HomeAddressCountryLabel;
    private javax.swing.JTextField HomeAddressState;
    private javax.swing.JLabel HomeAddressStateLabel;
    private javax.swing.JTextField HomeAddressStreetLine1;
    private javax.swing.JLabel HomeAddressStreetLine1Label;
    private javax.swing.JTextField HomeAddressStreetLine2;
    private javax.swing.JLabel HomeAddressStreetLine2Label;
    private javax.swing.JTextField HomeAddressZipCode;
    private javax.swing.JLabel HomeAddressZipCodeLabel;
    private javax.swing.JTextField LastName;
    private javax.swing.JLabel LastNameLabel;
    private javax.swing.JTextField LocalAddressCity;
    private javax.swing.JTextField LocalAddressCountry;
    private javax.swing.JLabel LocalAddressCountryLabel;
    private javax.swing.JTextField LocalAddressState;
    private javax.swing.JLabel LocalAddressStateLabel;
    private javax.swing.JTextField LocalAddressStreetLine1;
    private javax.swing.JTextField LocalAddressStreetLine2;
    private javax.swing.JTextField LocalAddressZipCode;
    private javax.swing.JLabel LocalAddressZipCodelabel;
    private javax.swing.JTextArea StreetAddress;
    private javax.swing.JLabel StreetAddressLabel;
    private javax.swing.JTextField WorkAddressCity;
    private javax.swing.JLabel WorkAddressCityLabel;
    private javax.swing.JTextField WorkAddressCountry;
    private javax.swing.JLabel WorkAddressCountryLabel;
    private javax.swing.JTextField WorkAddressState;
    private javax.swing.JLabel WorkAddressStatelabel;
    private javax.swing.JTextField WorkAddressStreetLine1;
    private javax.swing.JLabel WorkAddressStreetLine1Label;
    private javax.swing.JTextField WorkAddressStreetLine2;
    private javax.swing.JLabel WorkAddressStreetLine2Label;
    private javax.swing.JTextField WorkAddressZipCode;
    private javax.swing.JLabel WorkAddressZipCodeLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
