/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Business.Product;

/**
 *
 * @author vaniv
 */
public class ViewJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewJPanel
     */
    private Product product = new Product();
    public ViewJPanel(Product product) {
        initComponents();
        this.product = product;
        DisplayProductSupplier(product);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        UpdatedProductInformationLabel = new javax.swing.JLabel();
        SupplierInformation = new javax.swing.JPanel();
        IDLabel = new javax.swing.JLabel();
        NameLabel = new javax.swing.JLabel();
        CityLabel = new javax.swing.JLabel();
        StatusLabel = new javax.swing.JLabel();
        SupplierID = new javax.swing.JTextField();
        SupplierName = new javax.swing.JTextField();
        SupplierCity = new javax.swing.JTextField();
        SupplierStatus = new javax.swing.JTextField();
        ProductInformation = new javax.swing.JPanel();
        NameLabel1 = new javax.swing.JLabel();
        PriceLabel1 = new javax.swing.JLabel();
        AvailnumberLabel1 = new javax.swing.JLabel();
        DescriptionLabel1 = new javax.swing.JLabel();
        Name1 = new javax.swing.JTextField();
        Price1 = new javax.swing.JTextField();
        Availnumber1 = new javax.swing.JTextField();
        Description2 = new javax.swing.JScrollPane();
        Description1 = new javax.swing.JTextArea();

        setBackground(new java.awt.Color(102, 51, 0));

        UpdatedProductInformationLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        UpdatedProductInformationLabel.setText("UPDATED PRODUCT INFORMATION ");

        SupplierInformation.setBackground(new java.awt.Color(153, 102, 0));
        SupplierInformation.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "SUPPLIER INFORMATION\n", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Agency FB", 1, 18))); // NOI18N

        IDLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        IDLabel.setText("ID");

        NameLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        NameLabel.setText("NAME");

        CityLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        CityLabel.setText("CITY");

        StatusLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        StatusLabel.setText("STATUS");

        SupplierID.setFont(new java.awt.Font("Agency FB", 0, 18)); // NOI18N

        SupplierName.setFont(new java.awt.Font("Agency FB", 0, 18)); // NOI18N
        SupplierName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SupplierNameActionPerformed(evt);
            }
        });

        SupplierCity.setFont(new java.awt.Font("Agency FB", 0, 18)); // NOI18N

        SupplierStatus.setFont(new java.awt.Font("Agency FB", 0, 18)); // NOI18N

        javax.swing.GroupLayout SupplierInformationLayout = new javax.swing.GroupLayout(SupplierInformation);
        SupplierInformation.setLayout(SupplierInformationLayout);
        SupplierInformationLayout.setHorizontalGroup(
            SupplierInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SupplierInformationLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(SupplierInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(IDLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(NameLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(CityLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(StatusLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                .addGroup(SupplierInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SupplierID, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SupplierName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SupplierCity, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SupplierStatus, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26))
        );

        SupplierInformationLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {SupplierCity, SupplierID, SupplierName, SupplierStatus});

        SupplierInformationLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {CityLabel, IDLabel, NameLabel, StatusLabel});

        SupplierInformationLayout.setVerticalGroup(
            SupplierInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SupplierInformationLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(SupplierInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(SupplierInformationLayout.createSequentialGroup()
                        .addGroup(SupplierInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(IDLabel)
                            .addComponent(SupplierID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(41, 41, 41)
                        .addGroup(SupplierInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(SupplierName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NameLabel))
                        .addGap(62, 62, 62)
                        .addComponent(CityLabel))
                    .addComponent(SupplierCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60)
                .addGroup(SupplierInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(StatusLabel)
                    .addComponent(SupplierStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        SupplierInformationLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {SupplierCity, SupplierID, SupplierName, SupplierStatus});

        SupplierInformationLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {CityLabel, IDLabel, NameLabel, StatusLabel});

        ProductInformation.setBackground(new java.awt.Color(153, 102, 0));
        ProductInformation.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "PRODUCT INFORMATION\n", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N

        NameLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        NameLabel1.setText("NAME");

        PriceLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        PriceLabel1.setText("PRICE");

        AvailnumberLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        AvailnumberLabel1.setText("AVAILABLE NUMBER");

        DescriptionLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        DescriptionLabel1.setText("DESCRIPTION");

        Name1.setFont(new java.awt.Font("Agency FB", 0, 18)); // NOI18N

        Price1.setFont(new java.awt.Font("Agency FB", 0, 18)); // NOI18N

        Availnumber1.setFont(new java.awt.Font("Agency FB", 0, 18)); // NOI18N

        Description1.setColumns(20);
        Description1.setFont(new java.awt.Font("Agency FB", 0, 18)); // NOI18N
        Description1.setRows(5);
        Description2.setViewportView(Description1);

        javax.swing.GroupLayout ProductInformationLayout = new javax.swing.GroupLayout(ProductInformation);
        ProductInformation.setLayout(ProductInformationLayout);
        ProductInformationLayout.setHorizontalGroup(
            ProductInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProductInformationLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(ProductInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ProductInformationLayout.createSequentialGroup()
                        .addGroup(ProductInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ProductInformationLayout.createSequentialGroup()
                                .addComponent(NameLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Name1, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ProductInformationLayout.createSequentialGroup()
                                .addComponent(PriceLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Price1, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ProductInformationLayout.createSequentialGroup()
                                .addComponent(AvailnumberLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Availnumber1, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(ProductInformationLayout.createSequentialGroup()
                        .addComponent(DescriptionLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Description2, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(32, Short.MAX_VALUE))))
        );

        ProductInformationLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {AvailnumberLabel1, DescriptionLabel1, NameLabel1, PriceLabel1});

        ProductInformationLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {Availnumber1, Name1, Price1});

        ProductInformationLayout.setVerticalGroup(
            ProductInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProductInformationLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(ProductInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(ProductInformationLayout.createSequentialGroup()
                        .addGroup(ProductInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(NameLabel1)
                            .addComponent(Name1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(41, 41, 41)
                        .addGroup(ProductInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Price1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PriceLabel1))
                        .addGap(62, 62, 62)
                        .addComponent(AvailnumberLabel1))
                    .addComponent(Availnumber1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(61, 61, 61)
                .addGroup(ProductInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DescriptionLabel1)
                    .addComponent(Description2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        ProductInformationLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {AvailnumberLabel1, DescriptionLabel1, NameLabel1, PriceLabel1});

        ProductInformationLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {Availnumber1, Name1, Price1});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(SupplierInformation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(ProductInformation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(291, 291, 291)
                        .addComponent(UpdatedProductInformationLabel)))
                .addContainerGap(131, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(UpdatedProductInformationLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(SupplierInformation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ProductInformation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(175, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
   //To display Product and Supplier information 
    public void DisplayProductSupplier(Product product){
        String Name =product.getName();
        Name1.setText(Name);
        String Price = product.getPrice();
        Price1.setText(Price);
        String Availnum = product.getAvailNum();
        Availnumber1.setText(Availnum);
        String Description = product.getDescription();
        Description1.setText(Description);
        
        String SID = product.getSupplier().getID();
        SupplierID.setText(SID);
        String SName = product.getSupplier().getSName();
        SupplierName.setText(SName);
        String SCity = product.getSupplier().getCity();
        SupplierCity.setText(SCity);
        String SStatus = product.getSupplier().getStatus();
        SupplierStatus.setText(SStatus);
        
    }
    private void SupplierNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SupplierNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SupplierNameActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Availnumber1;
    private javax.swing.JLabel AvailnumberLabel1;
    private javax.swing.JLabel CityLabel;
    private javax.swing.JTextArea Description1;
    private javax.swing.JScrollPane Description2;
    private javax.swing.JLabel DescriptionLabel1;
    private javax.swing.JLabel IDLabel;
    private javax.swing.JTextField Name1;
    private javax.swing.JLabel NameLabel;
    private javax.swing.JLabel NameLabel1;
    private javax.swing.JTextField Price1;
    private javax.swing.JLabel PriceLabel1;
    private javax.swing.JPanel ProductInformation;
    private javax.swing.JLabel StatusLabel;
    private javax.swing.JTextField SupplierCity;
    private javax.swing.JTextField SupplierID;
    private javax.swing.JPanel SupplierInformation;
    private javax.swing.JTextField SupplierName;
    private javax.swing.JTextField SupplierStatus;
    private javax.swing.JLabel UpdatedProductInformationLabel;
    // End of variables declaration//GEN-END:variables
}
